"""add amount

Revision ID: 2dc3fe3ae229
Revises: 69b04ef6e6d9
Create Date: 2026-06-03 00:32:10.179028

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dc3fe3ae229"
down_revision: Union[str, Sequence[str], None] = "69b04ef6e6d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###
    op.execute("""
        UPDATE orders
        SET amount = quantity * 0
        WHERE amount IS NULL
    """)
    # 3. делаем колонку NOT NULL
    op.alter_column(
        "orders",
        "amount",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "amount")
    # ### end Alembic commands ###
