"""idempotency_key add to orders

Revision ID: 69b04ef6e6d9
Revises: cc869787ee42
Create Date: 2026-05-23 22:39:58.633590

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69b04ef6e6d9"
down_revision: Union[str, Sequence[str], None] = "cc869787ee42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("idempotency_key", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "orders", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_column("orders", "idempotency_key")
    # ### end Alembic commands ###
