"""change InboxEvent

Revision ID: 89fd5874f340
Revises: 9ff6fae469e3
Create Date: 2026-06-04 20:46:42.635445

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89fd5874f340"
down_revision: Union[str, Sequence[str], None] = "9ff6fae469e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inbox", sa.Column("order_id", sa.Text(), nullable=False))
    op.add_column("inbox", sa.Column("shipment_id", sa.Text(), nullable=False))
    op.drop_constraint(op.f("inbox_event_id_key"), "inbox", type_="unique")
    op.create_unique_constraint(None, "inbox", ["shipment_id"])
    op.drop_column("inbox", "event_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inbox", sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "inbox", type_="unique")
    op.create_unique_constraint(
        op.f("inbox_event_id_key"),
        "inbox",
        ["event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("inbox", "shipment_id")
    op.drop_column("inbox", "order_id")
    # ### end Alembic commands ###
