"""uuid to str

Revision ID: aec7decc2f0f
Revises: b67c6de8b268
Create Date: 2026-05-23 20:13:05.210148

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aec7decc2f0f"
down_revision: Union[str, Sequence[str], None] = "b67c6de8b268"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "item_id",
        existing_type=sa.UUID(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "item_id",
        existing_type=sa.Text(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "user_id",
        existing_type=sa.Text(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
